config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',     to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/work',     to: 'static_pages#work'
  get  '/signup',   to: 'users#new'
  post '/signup',   to: 'users#create'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'invalid email/password combination'
      render'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def work
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
                      :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Pomodoro Worker"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Pomodoro Worker</a>
    by <a href="https://twitter.com/bermuwater">bermu water</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <!--<li><a href="http://news.railstutorial.org/">News</a></li>-->
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>

<!--jQuery-->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<!--Popper.js-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<!--Bootstrap JS-->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- Sweet Alert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<% javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>

<%= render 'layouts/shim' %>

app/views/layouts/_header.html.erb
<!--<header class="navbar nabvar-expand navbar-light navbar-fixed-top" style="background-color: #e3f2fd;">-->
<header class="navbar nabvar-expand navbar-dark navbar-fixed-top">
  <div class="container">
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
      <%= link_to "pomodoro worker", root_path, id: "logo", class: "navbar-brand" %>
      <ul class="navbar-nav ml-auto">
        <!-- 共通 -->
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Work", work_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Help", help_path, class: "nav-link" %>
        </li>
        <!-- ログイン時 -->
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Users", '#', class: "nav-link" %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              Account
            </a>
            <div class="dropdown-menu">
              <%= link_to "Profile", current_user, class: "dropdown-item" %>
              <%= link_to "Settings", '#', class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
          </li>
        <!-- ログアウト時 -->
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_work_js.html.erb
<script>
  $(function() {
    'use strict';
    
    var timer = document.getElementById('timer');
    var min = document.getElementById('min');
    var min_plus = document.getElementById('min-plus');
    var min_minus = document.getElementById('min-minus');
    var sec = document.getElementById('sec');
    var sec_plus = document.getElementById('sec-plus');
    var sec_minus = document.getElementById('sec-minus');
    var reset = document.getElementById('reset');
    var start = document.getElementById('start');
    var timer_name = document.getElementById('timer-name');
    var vol_icon = document.getElementById('vol-icon');
    var startTime;
    var timeLeft = 0;
    // var timeToCountDown = 1800000;
    var timeToCountDown = 1000;
    
    // var intervalTime = 300000;
    var intervalTime = 1000;
    var timerId;
    var isRunning = false;
    // "Reset クリック時はキャンセル音のみ鳴らす"
    var clickReset = false;
    var masterVolume = 0.50;
    
    // ボタン連打に対応
    function playSound(sound) {
      var snd = document.getElementById(sound);
      snd.volume = masterVolume;
      snd.currentTime = 0;
      snd.play();
    }
    
    function updateTimer(t) {
      var d = new Date(t);
      var m = d.getMinutes();
      var s = d.getSeconds();
      var ms = d.getMilliseconds();
      var timerString;
      // 文字列＋数値 は 文字列になる。末尾から（-【取り出す桁数】）
      m = ('0' + m).slice(-2);
      s = ('0' + s).slice(-2);
      ms = ('00' + ms).slice(-3);
      timerString = m + ':' + s + '.' + ms;
      timer.textContent = timerString;
      // document.title =  timerString;
    
      // 時間が未設定の時は、設定ボタンのみ有効
      if (t > 0) {
        $("#start").prop('disabled', false);
        if (isRunning === true) {
          $("#reset").prop('disabled', true);
        } else {
          $("#reset").prop('disabled', false);
        }
      } else {
        $("#start").prop('disabled', true);
        $("#reset").prop('disabled', true);
        btnTimeDisabled();
      }
    }
    
    function countDown() {
      timerId = setTimeout(function() {
        timeLeft = timeToCountDown - (Date.now() - startTime);
        if (timeLeft < 0) {
          isRunning = false;
          if (clickReset == false) {
            playSound("decision6");
          }
          clickReset = false;
          start.innerHTML = '<i class="fas fa-play play-style"></i>'
          clearTimeout(timerId);
          timeLeft = 0;
          timeToCountDown = 0;
          updateTimer(timeLeft);
          $("#reset").prop('disabled', true);
          memo();
          return;
        }
        updateTimer(timeLeft);
        countDown();
      }, 10);
    }
    
    function btnTimeDisabled() {
      if (isRunning === true) {
        $("#min").prop('disabled', true);
        $("#min-plus").prop('disabled', true);
        $("#min-minus").prop('disabled', true);
        $("#sec").prop('disabled', true);
        $("#sec-plus").prop('disabled', true);
        $("#sec-minus").prop('disabled', true);
      } else {
        $("#min").prop('disabled', false);
        $("#min-plus").prop('disabled', false);
        $("#min-minus").prop('disabled', false);
        $("#sec").prop('disabled', false);
        $("#sec-plus").prop('disabled', false);
        $("#sec-minus").prop('disabled', false);
      }
    }
    
    
    function interval() {
      let timerInterval
      Swal.fire({
        icon: "success",
        title: "Time to take a break!",
        html: 'Your Life Span is <b></b>',
        timer: intervalTime * 2,
        timerProgressBar: true,
        onBeforeOpen: () => {
          timerInterval = setInterval(() => {
            const content = Swal.getContent()
            if (content) {
              const b = content.querySelector('b')
              if (b) {
                let intervalLeft = Swal.getTimerLeft();
                let m = Math.floor(intervalLeft / 60000);
                let s = Math.floor((intervalLeft % 60000) / 1000);
                m = ('0' + m).slice(-2);
                s = ('0' + s).slice(-2);
                b.textContent = m + ':' + s;
              }
            }
          }, 100)
        },
        onClose: () => {
          clearInterval(timerInterval)
        }
      }).then((result) => {
        if (result.dismiss === Swal.DismissReason.timer) {
          playSound("bath-out1");
        }
      })
    }
    
    function memo() {
      Swal.fire({
        title: 'タスクへメモを残す',
        html : '残すか残さないかは自由だ',
        input : 'textarea',
        inputPlaceholder: '次の５分を有効に使うがよい。'
      }).then(function(result) {
        if( result.value ){
          console.log(result.value);
        }
        playSound("bath-thapon1");
        interval();
      });
      timeToCountDown = intervalTime;
      updateTimer(intervalTime);
    }
    
    
    $('#vol-icon').on('click',function(){
      if (vol_icon.innerHTML.indexOf('up') !== -1) {
        vol_icon.innerHTML = '<i class="fas fa-volume-mute mute-style"></i>';
        masterVolume = 0;
      } else {
        vol_icon.innerHTML = '<i class="fas fa-volume-up vol-style"></i>';
        masterVolume = 0.50;
        playSound("decision22");
      }
    });
    
    start.addEventListener('click', function() {
      if (isRunning === false) {
        isRunning = true;
        btnTimeDisabled();
        start.innerHTML = '<i class="fas fa-pause pause-style"></i>';
        startTime = Date.now();
        countDown();
      } else {
        isRunning = false;
        $("#reset").prop('disabled', false);
        btnTimeDisabled();
        start.innerHTML = '<i class="fas fa-play play-style"></i>';
        timeToCountDown = timeLeft;
        clearTimeout(timerId);
      }
    });
    
    reset.addEventListener('click', function() {
      clickReset = true;
      playSound("cancel6");
      timeToCountDown = 0;
      $("#reset").prop('disabled', true);
      updateTimer(timeToCountDown);
    });
    
    min_plus.addEventListener('click', function() {
      clickReset = false;
      playSound("cursor1");
      timeToCountDown += 60 * 1000;
      if (timeToCountDown >= 60 * 60 * 1000) {
        timeToCountDown = 0;
      }
      updateTimer(timeToCountDown);
    });
    
    min_minus.addEventListener('click', function() {
      clickReset = false;
      playSound("cursor1");
      timeToCountDown -= 60 * 1000;
      if (timeToCountDown < 0) {
        timeToCountDown = 0;
      }
      updateTimer(timeToCountDown);
    });
    
    sec_plus.addEventListener('click', function() {
      clickReset = false;
      playSound("cursor2");
      timeToCountDown += 1000;
      if (timeToCountDown >= 60 * 60 * 1000) {
        timeToCountDown = 0;
      }
      updateTimer(timeToCountDown);
    });
    
    sec_minus.addEventListener('click', function() {
      clickReset = false;
      playSound("cursor2");
      timeToCountDown -= 1000;
      if (timeToCountDown < 0) {
        timeToCountDown = 0;
      }
      updateTimer(timeToCountDown);
    });
    
    timer_name.addEventListener('click', function() {
      playSound("nannarito");
    });
    
    
    // 分 選択
    $('#min-sel > .dropdown-item').on('click', function(){
      var min_sel = ($(this).attr('value'));
      // var minutes = Math.floor(timeToCountDown / 60000);
      var seconds = Math.floor((timeToCountDown % 60000) / 1000);
      var millis = (timeToCountDown % 60000) % 1000;
  
      timeToCountDown = min_sel * 60 * 1000 + seconds * 1000 + millis;
      updateTimer(timeToCountDown);
    });
  
    // 秒 選択
    $('#sec-sel > .dropdown-item').on('click', function(){
      var sec_sel = ($(this).attr('value'));
      var minutes = Math.floor(timeToCountDown / 60000);
      // var seconds = Math.floor((timeToCountDown % 60000) / 1000);
      var millis = (timeToCountDown % 60000) % 1000;
  
      timeToCountDown = minutes * 60 * 1000 + sec_sel * 1000 + millis;
      updateTimer(timeToCountDown);
    });
    
    
    
    // updateTimer(1800000);
    updateTimer(1000);

  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render 'layouts/head' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>ポモドーロ・テクニックとは...</h1>
<h2>
  仕事や勉強、家事などのタスクを25分間続けた後に5分の休憩を取り、そのサイクルを最大4回続けるという時間管理術である</br>
  確かな研究に基づいているのです。
</h2>
<h3>
  (参考URL)<a href="https://www.newsweekjapan.jp/stories/carrier/2019/03/post-11867.php">
ポモドーロ・テクニック：世界が実践する時間管理術はこうして生まれた</a>
</h3>
<h3>
  休憩はこまめに取った方が生産性は上がります！！
</h3>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>お問い合わせ</h1>
<p>
  こちらまで
  <a href="https://twitter.com/bermuwater">管理人Twitter</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>使い方</h1>
<ol>
  <li>Twitterアカウントにログインします</li>
  <li>タイマー時間をセットします</li>
  <li>作業のお供に動画でも流して見よう</br>
      ※自然音がおすすめです
  </li>
</ol>
<p>充実した時間になりますように</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Pomodoro Technique</h1>
  <p>ポモドーロテクニックの世界へようこそ</p>
  <h2>トマトのアイコン追加しようかな？</h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/static_pages/work.html.erb
<% provide(:title, "Work") %>

<div id="work-body">
  <!--    <div class="cover text-white text-left py-5">-->
  <!--      <h1 class="display-3 mb-5 w-75">Watch Out!</h1>-->
  <!--    </div>-->
  
  <section class="container--extend">
    <div class="clearfix">
      <h2 class="display-5 font-weight-bolder mb-2" id="timer-name">Timer
        <h4 id="vol-slide">
          <span id="vol-icon">
            <i class="fas fa-volume-up vol-style"></i>
          </span>
        </h4>
      </h2>
    </div>
  
    <div class="shadow border border-dark" id="timer">00:00.000</div>
    <!-- <div class="shadow border border-dark" id="timer">30:00.000</div> -->
    <div class="controls">
  
      <!-- 分 セット -->
      <div class="dropdown dropright">
        <button class="btn btn-primary btn-lg dropdown-toggle h-100" id="min" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Min
        </button>
        <div class="dropdown-menu" aria-labelledby="Min" id="min-sel">
          <script>
            var i;
            for( i=0; i<12; i++ ){
              document.write('<a class="dropdown-item" value="'+5*i+'">'+5*i+'</a>');
            }
          </script>
        </div>
      </div>
      <div class="btn-group-vertical">
        <button class="btn btn-outline-primary btn-sm h-50" id="min-plus">+</button>
        <button class="btn btn-outline-primary btn-sm h-50" id="min-minus">-</button>
      </div>
  
      <!-- 秒 セット -->
      <div class="dropdown dropright">
        <button class="btn btn-info btn-lg dropdown-toggle h-100" id="sec" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sec
        </button>
        <div class="dropdown-menu" aria-labelledby="Sec" id="sec-sel">
          <script>
            var i;
            for( i=0; i<12; i++ ){
              document.write('<a class="dropdown-item" value="'+5*i+'">'+5*i+'</a>');
            }
          </script>
        </div>
      </div>
      <div class="btn-group-vertical">
        <button class="btn btn-outline-info btn-sm h-50" id="sec-plus">+</button>
        <button class="btn btn-outline-info btn-sm h-50" id="sec-minus">-</button>
      </div>        
  
      <button class="btn btn-outline-dark btn-lg h-100" id="reset" disabled="disabled">
        <i class="fas fa-stop stop-style"></i>
      </button>
  
      <button class="btn btn-secondary btn-lg h-100" id="start" disabled="disabled">
        <!-- javascriptで fa-play と fa-pause の切替 -->
        <i class="fas fa-play play-style"></i>
      </button> 
  
    </div>
  </section>
  
  <section class="text-center">
    <h2 class="pt-4">With Work</h2>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/shiOb5Tuea0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </section>
  
  <section class="bg-light text-center py-4">
    <h2 class="mb-3" id="table-title">Done Today</h2>
    <div class="container">
      <table class="table table-hover table-dark table-sm">
        <thead>
          <tr>
            <th style="width:10%">lap</th>
            <th style="width:15%">time</th>
            <th style="width:15%">start</th>
            <th style="width:60%">task</th>
          </tr>
        </thead>
        <tbody>
          <tr><td>1</td><td>30m</td><td>08:12</td><td>ドットインストール</td></tr>
          <tr><td>2</td><td>15m</td><td>08:42</td><td>読書</td></tr>
          <tr><td>3</td><td>40m</td><td>16:35</td><td>ポートフォリオ作成</td></tr>
        </tbody>
      </table>
    </div>
  </section>
  

  <section>
    <%= audio_tag("cursor1.mp3",id:"cursor1") %>
    <%= audio_tag("cursor2.mp3",id:"cursor2") %>
    <%= audio_tag("cancel6.mp3",id:"cancel6") %>
    <%= audio_tag("decision6.mp3",id:"decision6") %>
    <%= audio_tag("decision22.mp3",id:"decision22") %>
    <%= audio_tag("bath-thapon1.mp3",id:"bath-thapon1") %>
    <%= audio_tag("bath-out1.mp3",id:"bath-out1") %>
    <%= audio_tag("nannarito.mp3",id:"nannarito") %>
  </section>
  
  <!--work用のjavascript-->
  <%= render 'layouts/work_js' %>
  
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>ユーザー登録</h1>
<p>Twitter アカウントで登録したい</p>

<div class="row">
  <!--<div class="col-md-6 col-md-offset-3">-->
  <div class="col-lg-6 .offset-lg-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%# form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confimation, "Confirmation" %>
      <%= f.password_field :password_confimation, class: 'form-control' %>
      
      <%= f.submit "アカウント作成", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <asside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>        
    </section>
  </asside>
</div>